name: Support Request
description: Request support between two or more mods.
labels: ["Support"]
body:
- type: checkboxes
  attributes:
    label: Support Notice
    description: There is some support that this mod explicitly **will not add**, listed in [the blacklist](BLACKLIST.md). Please read the blacklist before you request support.
    options:
      - label: I have read the blacklist and confirmed that I am not requesting blacklisted support.
        required: true
- type: input
  attributes:
    label: Primary Mod
    description: |
      The mod that adds the content/system to add support for.
      (For example, Thorium Mod adds the enemy repellent system.)
  validations:
    required: true
- type: input
  attributes:
    label: Support Mod(s)
    description: |
      The mod that adds the content to be supported.
      (For example, Liber Creaturarum adds bat-like enemies that could be repelled by Thorium Mod's Bat Repellent.)
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the support?
    description: |
      What would you like to see supported between these mods?
  validations:
    required: true